cc.out:client.o convert.o math.o proc.o
	gcc client.o convert.o math.o proc.o -o cc.out
client.o:client.c
	gcc -c client.c -o client.o
convert.o:convert.c
	gcc -c convert.c -o convert.o
math.o:math.c
	gcc -c math.c -o math.o
proc.o:proc.c
	gcc -c proc.c -o proc.o
